### ISSUE TITLE
[CRITICAL] Ote does not work :'(

### ISSUE THREAD

**Issue by solidjobs** [solidjobs/webapp#23]
How to reproduce:

- Log in https://app.solidjobs.org/login
- Open Ote assistant with Ote icon on bottom-right corner
- Select "Iniciar conversación".
- Ote keeps loading without result

Expected behavior

- Log in https://app.solidjobs.org/login
- Open Ote assistant with Ote icon on bottom-right corner
- Select "Iniciar conversación".
- Ote is talking with you :)

**Comment by hanschrome** [comment]
Automatic deployment was not installing the needed dependencies.
