### ISSUE TITLE
[CRITICAL] CV PDF rendering is not working

### ISSUE THREAD

**Issue by solidjobs** [solidjobs/webapp#24]
How to reproduce:

- Log in https://app.solidjobs.org/login
- Goes to tab "3. Exportar"
- Card keeps loading until an error is shown

Expected behavior

- Log in https://app.solidjobs.org/login
- Goes to tab "3. Exportar"
- You can download your CV on PDF

**Comment by hanschrome** [comment]
Service it's not working since binary has issues on docker due to SSL dependences.

**Comment by hanschrome** [comment]
Updated SSL dependences.
